#init init_triangles()
#run update_triangles()
#draw triangle<triangles.vertices>(instance=triangles.instance1)
#draw triangle<triangles.vertices>(instance=triangles.instance2)
#draw triangle<triangles.vertices>(instance=triangles.instance3)
