patterns:
  i32: &i32
    label: '`i32` value'
    regex: '-?[0-9]+'
    min: -2147483648
    max: 2147483647
  u16: &u16
    label: '`u16` value'
    regex: '[0-9]+'
    min: 0
    max: 65535
  ident: &ident
    label: identifier
    regex: '[a-zA-Z_][a-zA-Z0-9_]*'
  parent_folder: &parent_folder
    label: "`~`"
    regex: '~'

priority: &priority !repeat
  max: 1
  group:
    - !token '<'
    - !pattern
      label: priority
      config: *i32
    - !token '>'

vertex_buffer: &vertex_buffer !repeat
  min: 1
  max: 1
  group:
    - !pattern
      label: vertex_buffer_var
      config: *ident
    - !repeat
      group:
        - !token '.'
        - !pattern
          label: vertex_buffer_field
          config: *ident

instance_buffer: &instance_buffer !repeat
  min: 1
  max: 1
  group:
    - !pattern
      label: instance_buffer_var
      config: *ident
    - !repeat
      group:
        - !token '.'
        - !pattern
          label: instance_buffer_field
          config: *ident

toggle_value_buffer: &toggle_value_buffer !repeat
  min: 1
  max: 1
  group:
    - !pattern
      label: toggle_value_buffer_var
      config: *ident
    - !repeat
      group:
        - !token '.'
        - !pattern
          label: toggle_value_buffer_field
          config: *ident

arg_value: &arg_value !repeat
  min: 1
  max: 1
  group:
    - !pattern
      label: arg_var
      config: *ident
    - !repeat
      group:
        - !token '.'
        - !pattern
          label: arg_field
          config: *ident

arg_pair: &arg_pair !repeat
  min: 1
  max: 1
  group:
    - !pattern
      label: arg_name
      config: *ident
    - !token '='
    - *arg_value

args: &args !repeat
  max: 1
  group:
    - *arg_pair
    - !repeat
      group:
        - !token ','
        - *arg_pair

item_path: &item_path !repeat
  min: 1
  max: 1
  group:
    - !repeat
      group:
        - !pattern
          label: path_segment
          config: *parent_folder
        - !token '.'
    - !pattern
      label: path_segment
      config: *ident
    - !repeat
      group:
        - !token '.'
        - !pattern
          label: path_segment
          config: *ident

module: &module
  - !pattern
    label: section_name
    config: *ident

compute_shader: &compute_shader
  - !repeat
    max: 3
    group:
      - !token ','
      - !pattern
        label: workgroup_count
        config: *u16
  - !token '>'
  - !pattern
    label: section_name
    config: *ident

render_shader: &render_shader
  - !token ','
  - !pattern
    label: vertex_type
    config: *ident
  - !token ','
  - !pattern
    label: instance_type
    config: *ident
  - !token '>'
  - !pattern
    label: section_name
    config: *ident

shader: &shader
  - !token '<'
  - !choice
    - token: 'compute'
      next: *compute_shader
    - token: 'render'
      next: *render_shader

run: &run
  - *priority
  - *item_path
  - !token '('
  - *args
  - !token ')'

draw: &draw
  - *priority
  - *item_path
  - !token '<'
  - *vertex_buffer
  - !token ','
  - *instance_buffer
  - !token '>'
  - !token '('
  - *args
  - !token ')'

toggle: &toggle
  - !token '<'
  - *toggle_value_buffer
  - !token '>'
  - *item_path

main:
  - !token '#'
  - !choice
    - token: 'mod'
      next: *module
    - token: 'shader'
      next: *shader
    - token: 'init'
      next: *run
    - token: 'run'
      next: *run
    - token: 'draw'
      next: *draw
    - token: 'import'
      next:
        - *item_path
    - token: 'toggle'
      next: *toggle
